Feature/johen
Intel-Code-Test-Study/coding-test-study pull request #18
Opened 2024-12-01 11:03 UTC by JohenIn

2024-12-01 11:09 UTC, CianJS requested changes
BJ1002_Turret.py, 두수덧셈.py 두 파일 모두 특정 폴더 안에 들어가 있지 않은 것 같습니다.
폴더 안에 담아주세요~

2024-12-01 11:09 UTC, CianJS commented on djskal.py
이 파일은 필요없어보입니다! 제거해주세요~

2024-12-02 00:48 UTC, wintrover5966 approved these changes

2024-12-02 01:16 UTC, CianJS commented
assignees 할당해주세요

2024-12-02 01:17 UTC, CianJS commented on BJ1002_Turret.py
hello world가 아니라 해당 파일이 삭제된 이유가 있을까요?

2024-12-02 01:34 UTC, CianJS commented
<img width="870" alt="스크린샷 2024-12-02 오전 10 34 04" src="https://github.com/user-attachments/assets/2c6c856f-5461-4777-8b22-d539c1fe35e6">

commit message는 저번에도 말씀드렸듯이 이 커밋이 어떤 행동을 했는지 또는 무슨 목적으로 작성된 코드인지 등 해당 커밋의 상태를 나타내는 메시지여야합니다.

2024-12-02 01:35 UTC, CianJS approved these changes
👍

2024-12-02 05:36 UTC, CianJS approved these changes

2024-12-02 05:37 UTC, merged